### PR TITLE
LPS-202418 Generic error when set read only in the relationship field after bind

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPS-202418](https://liferay.atlassian.net/browse/LPS-202418)

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by Artartur** [comment]
Just start reviewing!

**Comment by Artartur** [comment]
Hey @larissacribeiro, you did a nice work here! I'm waiting the BE team approves to close this PR.

**Comment by Artartur** [comment]
LGTM! 🎉

**Review by Artartur — APPROVED** [review]

**Pull request closed without merging**
